// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/aeroDist.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AeroDist_RegistrarEntidad_FullMethodName           = "/aeroDist.AeroDist/RegistrarEntidad"
	AeroDist_SolicitarInicio_FullMethodName            = "/aeroDist.AeroDist/SolicitarInicio"
	AeroDist_ObtenerEstadoInicial_FullMethodName       = "/aeroDist.AeroDist/ObtenerEstadoInicial"
	AeroDist_RealizarCheckIn_FullMethodName            = "/aeroDist.AeroDist/RealizarCheckIn"
	AeroDist_ObtenerTarjetaEmbarque_FullMethodName     = "/aeroDist.AeroDist/ObtenerTarjetaEmbarque"
	AeroDist_ObtenerAsientosDisponibles_FullMethodName = "/aeroDist.AeroDist/ObtenerAsientosDisponibles"
	AeroDist_ReservarAsiento_FullMethodName            = "/aeroDist.AeroDist/ReservarAsiento"
	AeroDist_ObtenerInformacionVuelo_FullMethodName    = "/aeroDist.AeroDist/ObtenerInformacionVuelo"
	AeroDist_EnviarActualizacionVuelo_FullMethodName   = "/aeroDist.AeroDist/EnviarActualizacionVuelo"
	AeroDist_SincronizarEstado_FullMethodName          = "/aeroDist.AeroDist/SincronizarEstado"
	AeroDist_ObtenerEstadoVuelo_FullMethodName         = "/aeroDist.AeroDist/ObtenerEstadoVuelo"
	AeroDist_SolicitarVoto_FullMethodName              = "/aeroDist.AeroDist/SolicitarVoto"
	AeroDist_AppendEntries_FullMethodName              = "/aeroDist.AeroDist/AppendEntries"
	AeroDist_ProponerOperacionPista_FullMethodName     = "/aeroDist.AeroDist/ProponerOperacionPista"
	AeroDist_AsignarPista_FullMethodName               = "/aeroDist.AeroDist/AsignarPista"
	AeroDist_LiberarPista_FullMethodName               = "/aeroDist.AeroDist/LiberarPista"
)

// AeroDistClient is the client API for AeroDist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AeroDistClient interface {
	// Registro e inicio
	RegistrarEntidad(ctx context.Context, in *RegistroRequest, opts ...grpc.CallOption) (*RegistroResponse, error)
	SolicitarInicio(ctx context.Context, in *InicioRequest, opts ...grpc.CallOption) (*InicioResponse, error)
	// Servicios para RYW (Coordinador -> Broker)
	ObtenerEstadoInicial(ctx context.Context, in *EstadoInicialRequest, opts ...grpc.CallOption) (*EstadoInicialResponse, error)
	RealizarCheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error)
	ObtenerTarjetaEmbarque(ctx context.Context, in *TarjetaRequest, opts ...grpc.CallOption) (*TarjetaResponse, error)
	// Servicios para Datanodes (Broker -> Datanodes)
	ObtenerAsientosDisponibles(ctx context.Context, in *AsientosRequest, opts ...grpc.CallOption) (*AsientosResponse, error)
	ReservarAsiento(ctx context.Context, in *ReservaRequest, opts ...grpc.CallOption) (*ReservaResponse, error)
	ObtenerInformacionVuelo(ctx context.Context, in *InfoVueloRequest, opts ...grpc.CallOption) (*InfoVueloResponse, error)
	//Servicio para actualizaciones de vuelos desde CSV
	EnviarActualizacionVuelo(ctx context.Context, in *ActualizacionVueloRequest, opts ...grpc.CallOption) (*ActualizacionVueloResponse, error)
	//Servicio para gossip entre datanodes
	SincronizarEstado(ctx context.Context, in *SincronizacionRequest, opts ...grpc.CallOption) (*SincronizacionResponse, error)
	// Servicios para Monotonic Reads
	ObtenerEstadoVuelo(ctx context.Context, in *EstadoVueloRequest, opts ...grpc.CallOption) (*EstadoVueloResponse, error)
	SolicitarVoto(ctx context.Context, in *SolicitudVoto, opts ...grpc.CallOption) (*RespuestaVoto, error)
	AppendEntries(ctx context.Context, in *SolicitudAppendEntries, opts ...grpc.CallOption) (*RespuestaAppendEntries, error)
	ProponerOperacionPista(ctx context.Context, in *PropuestaOperacion, opts ...grpc.CallOption) (*RespuestaPropuesta, error)
	// Servicios para Consenso de Pistas
	AsignarPista(ctx context.Context, in *SolicitudPista, opts ...grpc.CallOption) (*RespuestaPista, error)
	LiberarPista(ctx context.Context, in *SolicitudLiberar, opts ...grpc.CallOption) (*RespuestaPista, error)
}

type aeroDistClient struct {
	cc grpc.ClientConnInterface
}

func NewAeroDistClient(cc grpc.ClientConnInterface) AeroDistClient {
	return &aeroDistClient{cc}
}

func (c *aeroDistClient) RegistrarEntidad(ctx context.Context, in *RegistroRequest, opts ...grpc.CallOption) (*RegistroResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistroResponse)
	err := c.cc.Invoke(ctx, AeroDist_RegistrarEntidad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) SolicitarInicio(ctx context.Context, in *InicioRequest, opts ...grpc.CallOption) (*InicioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InicioResponse)
	err := c.cc.Invoke(ctx, AeroDist_SolicitarInicio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) ObtenerEstadoInicial(ctx context.Context, in *EstadoInicialRequest, opts ...grpc.CallOption) (*EstadoInicialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstadoInicialResponse)
	err := c.cc.Invoke(ctx, AeroDist_ObtenerEstadoInicial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) RealizarCheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckInResponse)
	err := c.cc.Invoke(ctx, AeroDist_RealizarCheckIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) ObtenerTarjetaEmbarque(ctx context.Context, in *TarjetaRequest, opts ...grpc.CallOption) (*TarjetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TarjetaResponse)
	err := c.cc.Invoke(ctx, AeroDist_ObtenerTarjetaEmbarque_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) ObtenerAsientosDisponibles(ctx context.Context, in *AsientosRequest, opts ...grpc.CallOption) (*AsientosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AsientosResponse)
	err := c.cc.Invoke(ctx, AeroDist_ObtenerAsientosDisponibles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) ReservarAsiento(ctx context.Context, in *ReservaRequest, opts ...grpc.CallOption) (*ReservaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReservaResponse)
	err := c.cc.Invoke(ctx, AeroDist_ReservarAsiento_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) ObtenerInformacionVuelo(ctx context.Context, in *InfoVueloRequest, opts ...grpc.CallOption) (*InfoVueloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoVueloResponse)
	err := c.cc.Invoke(ctx, AeroDist_ObtenerInformacionVuelo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) EnviarActualizacionVuelo(ctx context.Context, in *ActualizacionVueloRequest, opts ...grpc.CallOption) (*ActualizacionVueloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActualizacionVueloResponse)
	err := c.cc.Invoke(ctx, AeroDist_EnviarActualizacionVuelo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) SincronizarEstado(ctx context.Context, in *SincronizacionRequest, opts ...grpc.CallOption) (*SincronizacionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SincronizacionResponse)
	err := c.cc.Invoke(ctx, AeroDist_SincronizarEstado_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) ObtenerEstadoVuelo(ctx context.Context, in *EstadoVueloRequest, opts ...grpc.CallOption) (*EstadoVueloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstadoVueloResponse)
	err := c.cc.Invoke(ctx, AeroDist_ObtenerEstadoVuelo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) SolicitarVoto(ctx context.Context, in *SolicitudVoto, opts ...grpc.CallOption) (*RespuestaVoto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespuestaVoto)
	err := c.cc.Invoke(ctx, AeroDist_SolicitarVoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) AppendEntries(ctx context.Context, in *SolicitudAppendEntries, opts ...grpc.CallOption) (*RespuestaAppendEntries, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespuestaAppendEntries)
	err := c.cc.Invoke(ctx, AeroDist_AppendEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) ProponerOperacionPista(ctx context.Context, in *PropuestaOperacion, opts ...grpc.CallOption) (*RespuestaPropuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespuestaPropuesta)
	err := c.cc.Invoke(ctx, AeroDist_ProponerOperacionPista_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) AsignarPista(ctx context.Context, in *SolicitudPista, opts ...grpc.CallOption) (*RespuestaPista, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespuestaPista)
	err := c.cc.Invoke(ctx, AeroDist_AsignarPista_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeroDistClient) LiberarPista(ctx context.Context, in *SolicitudLiberar, opts ...grpc.CallOption) (*RespuestaPista, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespuestaPista)
	err := c.cc.Invoke(ctx, AeroDist_LiberarPista_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AeroDistServer is the server API for AeroDist service.
// All implementations must embed UnimplementedAeroDistServer
// for forward compatibility.
type AeroDistServer interface {
	// Registro e inicio
	RegistrarEntidad(context.Context, *RegistroRequest) (*RegistroResponse, error)
	SolicitarInicio(context.Context, *InicioRequest) (*InicioResponse, error)
	// Servicios para RYW (Coordinador -> Broker)
	ObtenerEstadoInicial(context.Context, *EstadoInicialRequest) (*EstadoInicialResponse, error)
	RealizarCheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error)
	ObtenerTarjetaEmbarque(context.Context, *TarjetaRequest) (*TarjetaResponse, error)
	// Servicios para Datanodes (Broker -> Datanodes)
	ObtenerAsientosDisponibles(context.Context, *AsientosRequest) (*AsientosResponse, error)
	ReservarAsiento(context.Context, *ReservaRequest) (*ReservaResponse, error)
	ObtenerInformacionVuelo(context.Context, *InfoVueloRequest) (*InfoVueloResponse, error)
	//Servicio para actualizaciones de vuelos desde CSV
	EnviarActualizacionVuelo(context.Context, *ActualizacionVueloRequest) (*ActualizacionVueloResponse, error)
	//Servicio para gossip entre datanodes
	SincronizarEstado(context.Context, *SincronizacionRequest) (*SincronizacionResponse, error)
	// Servicios para Monotonic Reads
	ObtenerEstadoVuelo(context.Context, *EstadoVueloRequest) (*EstadoVueloResponse, error)
	SolicitarVoto(context.Context, *SolicitudVoto) (*RespuestaVoto, error)
	AppendEntries(context.Context, *SolicitudAppendEntries) (*RespuestaAppendEntries, error)
	ProponerOperacionPista(context.Context, *PropuestaOperacion) (*RespuestaPropuesta, error)
	// Servicios para Consenso de Pistas
	AsignarPista(context.Context, *SolicitudPista) (*RespuestaPista, error)
	LiberarPista(context.Context, *SolicitudLiberar) (*RespuestaPista, error)
	mustEmbedUnimplementedAeroDistServer()
}

// UnimplementedAeroDistServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAeroDistServer struct{}

func (UnimplementedAeroDistServer) RegistrarEntidad(context.Context, *RegistroRequest) (*RegistroResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistrarEntidad not implemented")
}
func (UnimplementedAeroDistServer) SolicitarInicio(context.Context, *InicioRequest) (*InicioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarInicio not implemented")
}
func (UnimplementedAeroDistServer) ObtenerEstadoInicial(context.Context, *EstadoInicialRequest) (*EstadoInicialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerEstadoInicial not implemented")
}
func (UnimplementedAeroDistServer) RealizarCheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RealizarCheckIn not implemented")
}
func (UnimplementedAeroDistServer) ObtenerTarjetaEmbarque(context.Context, *TarjetaRequest) (*TarjetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerTarjetaEmbarque not implemented")
}
func (UnimplementedAeroDistServer) ObtenerAsientosDisponibles(context.Context, *AsientosRequest) (*AsientosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerAsientosDisponibles not implemented")
}
func (UnimplementedAeroDistServer) ReservarAsiento(context.Context, *ReservaRequest) (*ReservaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReservarAsiento not implemented")
}
func (UnimplementedAeroDistServer) ObtenerInformacionVuelo(context.Context, *InfoVueloRequest) (*InfoVueloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerInformacionVuelo not implemented")
}
func (UnimplementedAeroDistServer) EnviarActualizacionVuelo(context.Context, *ActualizacionVueloRequest) (*ActualizacionVueloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarActualizacionVuelo not implemented")
}
func (UnimplementedAeroDistServer) SincronizarEstado(context.Context, *SincronizacionRequest) (*SincronizacionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SincronizarEstado not implemented")
}
func (UnimplementedAeroDistServer) ObtenerEstadoVuelo(context.Context, *EstadoVueloRequest) (*EstadoVueloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerEstadoVuelo not implemented")
}
func (UnimplementedAeroDistServer) SolicitarVoto(context.Context, *SolicitudVoto) (*RespuestaVoto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarVoto not implemented")
}
func (UnimplementedAeroDistServer) AppendEntries(context.Context, *SolicitudAppendEntries) (*RespuestaAppendEntries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntries not implemented")
}
func (UnimplementedAeroDistServer) ProponerOperacionPista(context.Context, *PropuestaOperacion) (*RespuestaPropuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProponerOperacionPista not implemented")
}
func (UnimplementedAeroDistServer) AsignarPista(context.Context, *SolicitudPista) (*RespuestaPista, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AsignarPista not implemented")
}
func (UnimplementedAeroDistServer) LiberarPista(context.Context, *SolicitudLiberar) (*RespuestaPista, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LiberarPista not implemented")
}
func (UnimplementedAeroDistServer) mustEmbedUnimplementedAeroDistServer() {}
func (UnimplementedAeroDistServer) testEmbeddedByValue()                  {}

// UnsafeAeroDistServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AeroDistServer will
// result in compilation errors.
type UnsafeAeroDistServer interface {
	mustEmbedUnimplementedAeroDistServer()
}

func RegisterAeroDistServer(s grpc.ServiceRegistrar, srv AeroDistServer) {
	// If the following call pancis, it indicates UnimplementedAeroDistServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AeroDist_ServiceDesc, srv)
}

func _AeroDist_RegistrarEntidad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).RegistrarEntidad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_RegistrarEntidad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).RegistrarEntidad(ctx, req.(*RegistroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_SolicitarInicio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InicioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).SolicitarInicio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_SolicitarInicio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).SolicitarInicio(ctx, req.(*InicioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_ObtenerEstadoInicial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstadoInicialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).ObtenerEstadoInicial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_ObtenerEstadoInicial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).ObtenerEstadoInicial(ctx, req.(*EstadoInicialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_RealizarCheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).RealizarCheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_RealizarCheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).RealizarCheckIn(ctx, req.(*CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_ObtenerTarjetaEmbarque_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TarjetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).ObtenerTarjetaEmbarque(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_ObtenerTarjetaEmbarque_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).ObtenerTarjetaEmbarque(ctx, req.(*TarjetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_ObtenerAsientosDisponibles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsientosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).ObtenerAsientosDisponibles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_ObtenerAsientosDisponibles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).ObtenerAsientosDisponibles(ctx, req.(*AsientosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_ReservarAsiento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReservaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).ReservarAsiento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_ReservarAsiento_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).ReservarAsiento(ctx, req.(*ReservaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_ObtenerInformacionVuelo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoVueloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).ObtenerInformacionVuelo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_ObtenerInformacionVuelo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).ObtenerInformacionVuelo(ctx, req.(*InfoVueloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_EnviarActualizacionVuelo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActualizacionVueloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).EnviarActualizacionVuelo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_EnviarActualizacionVuelo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).EnviarActualizacionVuelo(ctx, req.(*ActualizacionVueloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_SincronizarEstado_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SincronizacionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).SincronizarEstado(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_SincronizarEstado_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).SincronizarEstado(ctx, req.(*SincronizacionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_ObtenerEstadoVuelo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstadoVueloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).ObtenerEstadoVuelo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_ObtenerEstadoVuelo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).ObtenerEstadoVuelo(ctx, req.(*EstadoVueloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_SolicitarVoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudVoto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).SolicitarVoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_SolicitarVoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).SolicitarVoto(ctx, req.(*SolicitudVoto))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudAppendEntries)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_AppendEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).AppendEntries(ctx, req.(*SolicitudAppendEntries))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_ProponerOperacionPista_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropuestaOperacion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).ProponerOperacionPista(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_ProponerOperacionPista_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).ProponerOperacionPista(ctx, req.(*PropuestaOperacion))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_AsignarPista_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudPista)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).AsignarPista(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_AsignarPista_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).AsignarPista(ctx, req.(*SolicitudPista))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeroDist_LiberarPista_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudLiberar)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeroDistServer).LiberarPista(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeroDist_LiberarPista_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeroDistServer).LiberarPista(ctx, req.(*SolicitudLiberar))
	}
	return interceptor(ctx, in, info, handler)
}

// AeroDist_ServiceDesc is the grpc.ServiceDesc for AeroDist service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AeroDist_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aeroDist.AeroDist",
	HandlerType: (*AeroDistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistrarEntidad",
			Handler:    _AeroDist_RegistrarEntidad_Handler,
		},
		{
			MethodName: "SolicitarInicio",
			Handler:    _AeroDist_SolicitarInicio_Handler,
		},
		{
			MethodName: "ObtenerEstadoInicial",
			Handler:    _AeroDist_ObtenerEstadoInicial_Handler,
		},
		{
			MethodName: "RealizarCheckIn",
			Handler:    _AeroDist_RealizarCheckIn_Handler,
		},
		{
			MethodName: "ObtenerTarjetaEmbarque",
			Handler:    _AeroDist_ObtenerTarjetaEmbarque_Handler,
		},
		{
			MethodName: "ObtenerAsientosDisponibles",
			Handler:    _AeroDist_ObtenerAsientosDisponibles_Handler,
		},
		{
			MethodName: "ReservarAsiento",
			Handler:    _AeroDist_ReservarAsiento_Handler,
		},
		{
			MethodName: "ObtenerInformacionVuelo",
			Handler:    _AeroDist_ObtenerInformacionVuelo_Handler,
		},
		{
			MethodName: "EnviarActualizacionVuelo",
			Handler:    _AeroDist_EnviarActualizacionVuelo_Handler,
		},
		{
			MethodName: "SincronizarEstado",
			Handler:    _AeroDist_SincronizarEstado_Handler,
		},
		{
			MethodName: "ObtenerEstadoVuelo",
			Handler:    _AeroDist_ObtenerEstadoVuelo_Handler,
		},
		{
			MethodName: "SolicitarVoto",
			Handler:    _AeroDist_SolicitarVoto_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _AeroDist_AppendEntries_Handler,
		},
		{
			MethodName: "ProponerOperacionPista",
			Handler:    _AeroDist_ProponerOperacionPista_Handler,
		},
		{
			MethodName: "AsignarPista",
			Handler:    _AeroDist_AsignarPista_Handler,
		},
		{
			MethodName: "LiberarPista",
			Handler:    _AeroDist_LiberarPista_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aeroDist.proto",
}
