// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: proto/aeroDist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistroRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TipoEntidad   string                 `protobuf:"bytes,1,opt,name=tipo_entidad,json=tipoEntidad,proto3" json:"tipo_entidad,omitempty"`
	IdEntidad     string                 `protobuf:"bytes,2,opt,name=id_entidad,json=idEntidad,proto3" json:"id_entidad,omitempty"`
	Direccion     string                 `protobuf:"bytes,3,opt,name=direccion,proto3" json:"direccion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistroRequest) Reset() {
	*x = RegistroRequest{}
	mi := &file_proto_aeroDist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroRequest) ProtoMessage() {}

func (x *RegistroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroRequest.ProtoReflect.Descriptor instead.
func (*RegistroRequest) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{0}
}

func (x *RegistroRequest) GetTipoEntidad() string {
	if x != nil {
		return x.TipoEntidad
	}
	return ""
}

func (x *RegistroRequest) GetIdEntidad() string {
	if x != nil {
		return x.IdEntidad
	}
	return ""
}

func (x *RegistroRequest) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

type RegistroResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistroResponse) Reset() {
	*x = RegistroResponse{}
	mi := &file_proto_aeroDist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroResponse) ProtoMessage() {}

func (x *RegistroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroResponse.ProtoReflect.Descriptor instead.
func (*RegistroResponse) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{1}
}

func (x *RegistroResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *RegistroResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type InicioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TipoEntidad   string                 `protobuf:"bytes,1,opt,name=tipo_entidad,json=tipoEntidad,proto3" json:"tipo_entidad,omitempty"`
	IdEntidad     string                 `protobuf:"bytes,2,opt,name=id_entidad,json=idEntidad,proto3" json:"id_entidad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InicioRequest) Reset() {
	*x = InicioRequest{}
	mi := &file_proto_aeroDist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InicioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InicioRequest) ProtoMessage() {}

func (x *InicioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InicioRequest.ProtoReflect.Descriptor instead.
func (*InicioRequest) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{2}
}

func (x *InicioRequest) GetTipoEntidad() string {
	if x != nil {
		return x.TipoEntidad
	}
	return ""
}

func (x *InicioRequest) GetIdEntidad() string {
	if x != nil {
		return x.IdEntidad
	}
	return ""
}

type InicioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PuedeIniciar  bool                   `protobuf:"varint,1,opt,name=puede_iniciar,json=puedeIniciar,proto3" json:"puede_iniciar,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InicioResponse) Reset() {
	*x = InicioResponse{}
	mi := &file_proto_aeroDist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InicioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InicioResponse) ProtoMessage() {}

func (x *InicioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InicioResponse.ProtoReflect.Descriptor instead.
func (*InicioResponse) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{3}
}

func (x *InicioResponse) GetPuedeIniciar() bool {
	if x != nil {
		return x.PuedeIniciar
	}
	return false
}

func (x *InicioResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type EstadoInicialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	VueloId       string                 `protobuf:"bytes,2,opt,name=vuelo_id,json=vueloId,proto3" json:"vuelo_id,omitempty"`
	StickyInfo    *StickyInfo            `protobuf:"bytes,3,opt,name=sticky_info,json=stickyInfo,proto3" json:"sticky_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstadoInicialRequest) Reset() {
	*x = EstadoInicialRequest{}
	mi := &file_proto_aeroDist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoInicialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoInicialRequest) ProtoMessage() {}

func (x *EstadoInicialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoInicialRequest.ProtoReflect.Descriptor instead.
func (*EstadoInicialRequest) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{4}
}

func (x *EstadoInicialRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *EstadoInicialRequest) GetVueloId() string {
	if x != nil {
		return x.VueloId
	}
	return ""
}

func (x *EstadoInicialRequest) GetStickyInfo() *StickyInfo {
	if x != nil {
		return x.StickyInfo
	}
	return nil
}

type EstadoInicialResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Exito               bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje             string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	AsientosDisponibles []string               `protobuf:"bytes,3,rep,name=asientos_disponibles,json=asientosDisponibles,proto3" json:"asientos_disponibles,omitempty"`
	TotalAsientos       int32                  `protobuf:"varint,4,opt,name=total_asientos,json=totalAsientos,proto3" json:"total_asientos,omitempty"`
	AsientosOcupados    int32                  `protobuf:"varint,5,opt,name=asientos_ocupados,json=asientosOcupados,proto3" json:"asientos_ocupados,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EstadoInicialResponse) Reset() {
	*x = EstadoInicialResponse{}
	mi := &file_proto_aeroDist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoInicialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoInicialResponse) ProtoMessage() {}

func (x *EstadoInicialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoInicialResponse.ProtoReflect.Descriptor instead.
func (*EstadoInicialResponse) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{5}
}

func (x *EstadoInicialResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *EstadoInicialResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *EstadoInicialResponse) GetAsientosDisponibles() []string {
	if x != nil {
		return x.AsientosDisponibles
	}
	return nil
}

func (x *EstadoInicialResponse) GetTotalAsientos() int32 {
	if x != nil {
		return x.TotalAsientos
	}
	return 0
}

func (x *EstadoInicialResponse) GetAsientosOcupados() int32 {
	if x != nil {
		return x.AsientosOcupados
	}
	return 0
}

type StickyInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TieneSesion     bool                   `protobuf:"varint,1,opt,name=tiene_sesion,json=tieneSesion,proto3" json:"tiene_sesion,omitempty"`
	DatanodeAddress string                 `protobuf:"bytes,2,opt,name=datanode_address,json=datanodeAddress,proto3" json:"datanode_address,omitempty"`
	ClienteId       string                 `protobuf:"bytes,3,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StickyInfo) Reset() {
	*x = StickyInfo{}
	mi := &file_proto_aeroDist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickyInfo) ProtoMessage() {}

func (x *StickyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StickyInfo.ProtoReflect.Descriptor instead.
func (*StickyInfo) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{6}
}

func (x *StickyInfo) GetTieneSesion() bool {
	if x != nil {
		return x.TieneSesion
	}
	return false
}

func (x *StickyInfo) GetDatanodeAddress() string {
	if x != nil {
		return x.DatanodeAddress
	}
	return ""
}

func (x *StickyInfo) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	VueloId       string                 `protobuf:"bytes,2,opt,name=vuelo_id,json=vueloId,proto3" json:"vuelo_id,omitempty"`
	Asiento       string                 `protobuf:"bytes,3,opt,name=asiento,proto3" json:"asiento,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StickyInfo    *StickyInfo            `protobuf:"bytes,5,opt,name=sticky_info,json=stickyInfo,proto3" json:"sticky_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_proto_aeroDist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{7}
}

func (x *CheckInRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *CheckInRequest) GetVueloId() string {
	if x != nil {
		return x.VueloId
	}
	return ""
}

func (x *CheckInRequest) GetAsiento() string {
	if x != nil {
		return x.Asiento
	}
	return ""
}

func (x *CheckInRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CheckInRequest) GetStickyInfo() *StickyInfo {
	if x != nil {
		return x.StickyInfo
	}
	return nil
}

type DatanodeAsignacion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClienteId       string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	DatanodeAddress string                 `protobuf:"bytes,2,opt,name=datanode_address,json=datanodeAddress,proto3" json:"datanode_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DatanodeAsignacion) Reset() {
	*x = DatanodeAsignacion{}
	mi := &file_proto_aeroDist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatanodeAsignacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatanodeAsignacion) ProtoMessage() {}

func (x *DatanodeAsignacion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatanodeAsignacion.ProtoReflect.Descriptor instead.
func (*DatanodeAsignacion) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{8}
}

func (x *DatanodeAsignacion) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *DatanodeAsignacion) GetDatanodeAddress() string {
	if x != nil {
		return x.DatanodeAddress
	}
	return ""
}

type CheckInResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Exito             bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje           string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	TarjetaEmbarqueId string                 `protobuf:"bytes,3,opt,name=tarjeta_embarque_id,json=tarjetaEmbarqueId,proto3" json:"tarjeta_embarque_id,omitempty"`
	AsientoAsignado   string                 `protobuf:"bytes,4,opt,name=asiento_asignado,json=asientoAsignado,proto3" json:"asiento_asignado,omitempty"`
	Asignacion        *DatanodeAsignacion    `protobuf:"bytes,5,opt,name=asignacion,proto3" json:"asignacion,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckInResponse) Reset() {
	*x = CheckInResponse{}
	mi := &file_proto_aeroDist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponse) ProtoMessage() {}

func (x *CheckInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponse.ProtoReflect.Descriptor instead.
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{9}
}

func (x *CheckInResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *CheckInResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *CheckInResponse) GetTarjetaEmbarqueId() string {
	if x != nil {
		return x.TarjetaEmbarqueId
	}
	return ""
}

func (x *CheckInResponse) GetAsientoAsignado() string {
	if x != nil {
		return x.AsientoAsignado
	}
	return ""
}

func (x *CheckInResponse) GetAsignacion() *DatanodeAsignacion {
	if x != nil {
		return x.Asignacion
	}
	return nil
}

type TarjetaRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClienteId         string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	TarjetaEmbarqueId string                 `protobuf:"bytes,2,opt,name=tarjeta_embarque_id,json=tarjetaEmbarqueId,proto3" json:"tarjeta_embarque_id,omitempty"`
	StickyInfo        *StickyInfo            `protobuf:"bytes,3,opt,name=sticky_info,json=stickyInfo,proto3" json:"sticky_info,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TarjetaRequest) Reset() {
	*x = TarjetaRequest{}
	mi := &file_proto_aeroDist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TarjetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TarjetaRequest) ProtoMessage() {}

func (x *TarjetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TarjetaRequest.ProtoReflect.Descriptor instead.
func (*TarjetaRequest) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{10}
}

func (x *TarjetaRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *TarjetaRequest) GetTarjetaEmbarqueId() string {
	if x != nil {
		return x.TarjetaEmbarqueId
	}
	return ""
}

func (x *TarjetaRequest) GetStickyInfo() *StickyInfo {
	if x != nil {
		return x.StickyInfo
	}
	return nil
}

type TarjetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	VueloId       string                 `protobuf:"bytes,3,opt,name=vuelo_id,json=vueloId,proto3" json:"vuelo_id,omitempty"`
	Asiento       string                 `protobuf:"bytes,4,opt,name=asiento,proto3" json:"asiento,omitempty"`
	Estado        string                 `protobuf:"bytes,5,opt,name=estado,proto3" json:"estado,omitempty"`
	ClienteId     string                 `protobuf:"bytes,6,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TarjetaResponse) Reset() {
	*x = TarjetaResponse{}
	mi := &file_proto_aeroDist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TarjetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TarjetaResponse) ProtoMessage() {}

func (x *TarjetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TarjetaResponse.ProtoReflect.Descriptor instead.
func (*TarjetaResponse) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{11}
}

func (x *TarjetaResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *TarjetaResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *TarjetaResponse) GetVueloId() string {
	if x != nil {
		return x.VueloId
	}
	return ""
}

func (x *TarjetaResponse) GetAsiento() string {
	if x != nil {
		return x.Asiento
	}
	return ""
}

func (x *TarjetaResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *TarjetaResponse) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

type AsientosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VueloId       string                 `protobuf:"bytes,1,opt,name=vuelo_id,json=vueloId,proto3" json:"vuelo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsientosRequest) Reset() {
	*x = AsientosRequest{}
	mi := &file_proto_aeroDist_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsientosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsientosRequest) ProtoMessage() {}

func (x *AsientosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsientosRequest.ProtoReflect.Descriptor instead.
func (*AsientosRequest) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{12}
}

func (x *AsientosRequest) GetVueloId() string {
	if x != nil {
		return x.VueloId
	}
	return ""
}

type AsientosResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Exito               bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje             string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	AsientosDisponibles []string               `protobuf:"bytes,3,rep,name=asientos_disponibles,json=asientosDisponibles,proto3" json:"asientos_disponibles,omitempty"`
	EstadoAsientos      map[string]bool        `protobuf:"bytes,4,rep,name=estado_asientos,json=estadoAsientos,proto3" json:"estado_asientos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AsientosResponse) Reset() {
	*x = AsientosResponse{}
	mi := &file_proto_aeroDist_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsientosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsientosResponse) ProtoMessage() {}

func (x *AsientosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsientosResponse.ProtoReflect.Descriptor instead.
func (*AsientosResponse) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{13}
}

func (x *AsientosResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *AsientosResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *AsientosResponse) GetAsientosDisponibles() []string {
	if x != nil {
		return x.AsientosDisponibles
	}
	return nil
}

func (x *AsientosResponse) GetEstadoAsientos() map[string]bool {
	if x != nil {
		return x.EstadoAsientos
	}
	return nil
}

type ReservaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VueloId       string                 `protobuf:"bytes,1,opt,name=vuelo_id,json=vueloId,proto3" json:"vuelo_id,omitempty"`
	Asiento       string                 `protobuf:"bytes,2,opt,name=asiento,proto3" json:"asiento,omitempty"`
	ClienteId     string                 `protobuf:"bytes,3,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservaRequest) Reset() {
	*x = ReservaRequest{}
	mi := &file_proto_aeroDist_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservaRequest) ProtoMessage() {}

func (x *ReservaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservaRequest.ProtoReflect.Descriptor instead.
func (*ReservaRequest) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{14}
}

func (x *ReservaRequest) GetVueloId() string {
	if x != nil {
		return x.VueloId
	}
	return ""
}

func (x *ReservaRequest) GetAsiento() string {
	if x != nil {
		return x.Asiento
	}
	return ""
}

func (x *ReservaRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *ReservaRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ReservaResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Exito             bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje           string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	TarjetaEmbarqueId string                 `protobuf:"bytes,3,opt,name=tarjeta_embarque_id,json=tarjetaEmbarqueId,proto3" json:"tarjeta_embarque_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReservaResponse) Reset() {
	*x = ReservaResponse{}
	mi := &file_proto_aeroDist_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservaResponse) ProtoMessage() {}

func (x *ReservaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservaResponse.ProtoReflect.Descriptor instead.
func (*ReservaResponse) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{15}
}

func (x *ReservaResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ReservaResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ReservaResponse) GetTarjetaEmbarqueId() string {
	if x != nil {
		return x.TarjetaEmbarqueId
	}
	return ""
}

type InfoVueloRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TarjetaEmbarqueId string                 `protobuf:"bytes,1,opt,name=tarjeta_embarque_id,json=tarjetaEmbarqueId,proto3" json:"tarjeta_embarque_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InfoVueloRequest) Reset() {
	*x = InfoVueloRequest{}
	mi := &file_proto_aeroDist_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoVueloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoVueloRequest) ProtoMessage() {}

func (x *InfoVueloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoVueloRequest.ProtoReflect.Descriptor instead.
func (*InfoVueloRequest) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{16}
}

func (x *InfoVueloRequest) GetTarjetaEmbarqueId() string {
	if x != nil {
		return x.TarjetaEmbarqueId
	}
	return ""
}

type InfoVueloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	VueloId       string                 `protobuf:"bytes,3,opt,name=vuelo_id,json=vueloId,proto3" json:"vuelo_id,omitempty"`
	Asiento       string                 `protobuf:"bytes,4,opt,name=asiento,proto3" json:"asiento,omitempty"`
	ClienteId     string                 `protobuf:"bytes,5,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	Estado        string                 `protobuf:"bytes,6,opt,name=estado,proto3" json:"estado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoVueloResponse) Reset() {
	*x = InfoVueloResponse{}
	mi := &file_proto_aeroDist_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoVueloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoVueloResponse) ProtoMessage() {}

func (x *InfoVueloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoVueloResponse.ProtoReflect.Descriptor instead.
func (*InfoVueloResponse) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{17}
}

func (x *InfoVueloResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *InfoVueloResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *InfoVueloResponse) GetVueloId() string {
	if x != nil {
		return x.VueloId
	}
	return ""
}

func (x *InfoVueloResponse) GetAsiento() string {
	if x != nil {
		return x.Asiento
	}
	return ""
}

func (x *InfoVueloResponse) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *InfoVueloResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type ActualizacionVueloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VueloId       string                 `protobuf:"bytes,1,opt,name=vuelo_id,json=vueloId,proto3" json:"vuelo_id,omitempty"`
	UpdateType    string                 `protobuf:"bytes,2,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"`
	UpdateValue   string                 `protobuf:"bytes,3,opt,name=update_value,json=updateValue,proto3" json:"update_value,omitempty"`
	SimTimeSec    int64                  `protobuf:"varint,4,opt,name=sim_time_sec,json=simTimeSec,proto3" json:"sim_time_sec,omitempty"`
	RelojVector   *VectorClock           `protobuf:"bytes,5,opt,name=reloj_vector,json=relojVector,proto3" json:"reloj_vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizacionVueloRequest) Reset() {
	*x = ActualizacionVueloRequest{}
	mi := &file_proto_aeroDist_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizacionVueloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizacionVueloRequest) ProtoMessage() {}

func (x *ActualizacionVueloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizacionVueloRequest.ProtoReflect.Descriptor instead.
func (*ActualizacionVueloRequest) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{18}
}

func (x *ActualizacionVueloRequest) GetVueloId() string {
	if x != nil {
		return x.VueloId
	}
	return ""
}

func (x *ActualizacionVueloRequest) GetUpdateType() string {
	if x != nil {
		return x.UpdateType
	}
	return ""
}

func (x *ActualizacionVueloRequest) GetUpdateValue() string {
	if x != nil {
		return x.UpdateValue
	}
	return ""
}

func (x *ActualizacionVueloRequest) GetSimTimeSec() int64 {
	if x != nil {
		return x.SimTimeSec
	}
	return 0
}

func (x *ActualizacionVueloRequest) GetRelojVector() *VectorClock {
	if x != nil {
		return x.RelojVector
	}
	return nil
}

type ActualizacionVueloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	NuevoReloj    *VectorClock           `protobuf:"bytes,3,opt,name=nuevo_reloj,json=nuevoReloj,proto3" json:"nuevo_reloj,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizacionVueloResponse) Reset() {
	*x = ActualizacionVueloResponse{}
	mi := &file_proto_aeroDist_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizacionVueloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizacionVueloResponse) ProtoMessage() {}

func (x *ActualizacionVueloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizacionVueloResponse.ProtoReflect.Descriptor instead.
func (*ActualizacionVueloResponse) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{19}
}

func (x *ActualizacionVueloResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ActualizacionVueloResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ActualizacionVueloResponse) GetNuevoReloj() *VectorClock {
	if x != nil {
		return x.NuevoReloj
	}
	return nil
}

type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clocks        map[string]int32       `protobuf:"bytes,1,rep,name=clocks,proto3" json:"clocks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_proto_aeroDist_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{20}
}

func (x *VectorClock) GetClocks() map[string]int32 {
	if x != nil {
		return x.Clocks
	}
	return nil
}

type EstadoDatanode struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	EstadosVuelos map[string]*EstadoVuelo `protobuf:"bytes,1,rep,name=estados_vuelos,json=estadosVuelos,proto3" json:"estados_vuelos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RelojVector   *VectorClock            `protobuf:"bytes,2,opt,name=reloj_vector,json=relojVector,proto3" json:"reloj_vector,omitempty"`
	DatanodeId    string                  `protobuf:"bytes,3,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstadoDatanode) Reset() {
	*x = EstadoDatanode{}
	mi := &file_proto_aeroDist_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoDatanode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoDatanode) ProtoMessage() {}

func (x *EstadoDatanode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoDatanode.ProtoReflect.Descriptor instead.
func (*EstadoDatanode) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{21}
}

func (x *EstadoDatanode) GetEstadosVuelos() map[string]*EstadoVuelo {
	if x != nil {
		return x.EstadosVuelos
	}
	return nil
}

func (x *EstadoDatanode) GetRelojVector() *VectorClock {
	if x != nil {
		return x.RelojVector
	}
	return nil
}

func (x *EstadoDatanode) GetDatanodeId() string {
	if x != nil {
		return x.DatanodeId
	}
	return ""
}

type EstadoVuelo struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	UltimoEstado        string                  `protobuf:"bytes,1,opt,name=ultimo_estado,json=ultimoEstado,proto3" json:"ultimo_estado,omitempty"`
	UltimaPuerta        string                  `protobuf:"bytes,2,opt,name=ultima_puerta,json=ultimaPuerta,proto3" json:"ultima_puerta,omitempty"`
	RelojEstado         *VectorClock            `protobuf:"bytes,3,opt,name=reloj_estado,json=relojEstado,proto3" json:"reloj_estado,omitempty"`
	UltimaActualizacion int64                   `protobuf:"varint,4,opt,name=ultima_actualizacion,json=ultimaActualizacion,proto3" json:"ultima_actualizacion,omitempty"`
	AsientosOcupados    map[string]bool         `protobuf:"bytes,5,rep,name=asientos_ocupados,json=asientosOcupados,proto3" json:"asientos_ocupados,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Tarjetas            map[string]*TarjetaInfo `protobuf:"bytes,6,rep,name=tarjetas,proto3" json:"tarjetas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EstadoVuelo) Reset() {
	*x = EstadoVuelo{}
	mi := &file_proto_aeroDist_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoVuelo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoVuelo) ProtoMessage() {}

func (x *EstadoVuelo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoVuelo.ProtoReflect.Descriptor instead.
func (*EstadoVuelo) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{22}
}

func (x *EstadoVuelo) GetUltimoEstado() string {
	if x != nil {
		return x.UltimoEstado
	}
	return ""
}

func (x *EstadoVuelo) GetUltimaPuerta() string {
	if x != nil {
		return x.UltimaPuerta
	}
	return ""
}

func (x *EstadoVuelo) GetRelojEstado() *VectorClock {
	if x != nil {
		return x.RelojEstado
	}
	return nil
}

func (x *EstadoVuelo) GetUltimaActualizacion() int64 {
	if x != nil {
		return x.UltimaActualizacion
	}
	return 0
}

func (x *EstadoVuelo) GetAsientosOcupados() map[string]bool {
	if x != nil {
		return x.AsientosOcupados
	}
	return nil
}

func (x *EstadoVuelo) GetTarjetas() map[string]*TarjetaInfo {
	if x != nil {
		return x.Tarjetas
	}
	return nil
}

type TarjetaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VueloId       string                 `protobuf:"bytes,1,opt,name=vuelo_id,json=vueloId,proto3" json:"vuelo_id,omitempty"`
	Asiento       string                 `protobuf:"bytes,2,opt,name=asiento,proto3" json:"asiento,omitempty"`
	ClienteId     string                 `protobuf:"bytes,3,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TarjetaInfo) Reset() {
	*x = TarjetaInfo{}
	mi := &file_proto_aeroDist_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TarjetaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TarjetaInfo) ProtoMessage() {}

func (x *TarjetaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TarjetaInfo.ProtoReflect.Descriptor instead.
func (*TarjetaInfo) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{23}
}

func (x *TarjetaInfo) GetVueloId() string {
	if x != nil {
		return x.VueloId
	}
	return ""
}

func (x *TarjetaInfo) GetAsiento() string {
	if x != nil {
		return x.Asiento
	}
	return ""
}

func (x *TarjetaInfo) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *TarjetaInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SincronizacionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EstadoRemitente *EstadoDatanode        `protobuf:"bytes,1,opt,name=estado_remitente,json=estadoRemitente,proto3" json:"estado_remitente,omitempty"`
	DatanodeOrigen  string                 `protobuf:"bytes,2,opt,name=datanode_origen,json=datanodeOrigen,proto3" json:"datanode_origen,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SincronizacionRequest) Reset() {
	*x = SincronizacionRequest{}
	mi := &file_proto_aeroDist_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SincronizacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SincronizacionRequest) ProtoMessage() {}

func (x *SincronizacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SincronizacionRequest.ProtoReflect.Descriptor instead.
func (*SincronizacionRequest) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{24}
}

func (x *SincronizacionRequest) GetEstadoRemitente() *EstadoDatanode {
	if x != nil {
		return x.EstadoRemitente
	}
	return nil
}

func (x *SincronizacionRequest) GetDatanodeOrigen() string {
	if x != nil {
		return x.DatanodeOrigen
	}
	return ""
}

type SincronizacionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Exito             bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje           string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	EstadoActualizado *EstadoDatanode        `protobuf:"bytes,3,opt,name=estado_actualizado,json=estadoActualizado,proto3" json:"estado_actualizado,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SincronizacionResponse) Reset() {
	*x = SincronizacionResponse{}
	mi := &file_proto_aeroDist_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SincronizacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SincronizacionResponse) ProtoMessage() {}

func (x *SincronizacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SincronizacionResponse.ProtoReflect.Descriptor instead.
func (*SincronizacionResponse) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{25}
}

func (x *SincronizacionResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *SincronizacionResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *SincronizacionResponse) GetEstadoActualizado() *EstadoDatanode {
	if x != nil {
		return x.EstadoActualizado
	}
	return nil
}

type EstadoVueloRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VueloId        string                 `protobuf:"bytes,1,opt,name=vuelo_id,json=vueloId,proto3" json:"vuelo_id,omitempty"`
	VersionCliente *VectorClock           `protobuf:"bytes,2,opt,name=version_cliente,json=versionCliente,proto3" json:"version_cliente,omitempty"`
	ClienteId      string                 `protobuf:"bytes,3,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EstadoVueloRequest) Reset() {
	*x = EstadoVueloRequest{}
	mi := &file_proto_aeroDist_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoVueloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoVueloRequest) ProtoMessage() {}

func (x *EstadoVueloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoVueloRequest.ProtoReflect.Descriptor instead.
func (*EstadoVueloRequest) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{26}
}

func (x *EstadoVueloRequest) GetVueloId() string {
	if x != nil {
		return x.VueloId
	}
	return ""
}

func (x *EstadoVueloRequest) GetVersionCliente() *VectorClock {
	if x != nil {
		return x.VersionCliente
	}
	return nil
}

func (x *EstadoVueloRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

type EstadoVueloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	VueloId       string                 `protobuf:"bytes,3,opt,name=vuelo_id,json=vueloId,proto3" json:"vuelo_id,omitempty"`
	Estado        string                 `protobuf:"bytes,4,opt,name=estado,proto3" json:"estado,omitempty"`
	Puerta        string                 `protobuf:"bytes,5,opt,name=puerta,proto3" json:"puerta,omitempty"`
	VersionActual *VectorClock           `protobuf:"bytes,6,opt,name=version_actual,json=versionActual,proto3" json:"version_actual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstadoVueloResponse) Reset() {
	*x = EstadoVueloResponse{}
	mi := &file_proto_aeroDist_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoVueloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoVueloResponse) ProtoMessage() {}

func (x *EstadoVueloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoVueloResponse.ProtoReflect.Descriptor instead.
func (*EstadoVueloResponse) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{27}
}

func (x *EstadoVueloResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *EstadoVueloResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *EstadoVueloResponse) GetVueloId() string {
	if x != nil {
		return x.VueloId
	}
	return ""
}

func (x *EstadoVueloResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *EstadoVueloResponse) GetPuerta() string {
	if x != nil {
		return x.Puerta
	}
	return ""
}

func (x *EstadoVueloResponse) GetVersionActual() *VectorClock {
	if x != nil {
		return x.VersionActual
	}
	return nil
}

type SolicitudVoto struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Termino          int32                  `protobuf:"varint,1,opt,name=termino,proto3" json:"termino,omitempty"`
	CandidatoId      string                 `protobuf:"bytes,2,opt,name=candidato_id,json=candidatoId,proto3" json:"candidato_id,omitempty"`
	UltimoIndiceLog  int32                  `protobuf:"varint,3,opt,name=ultimo_indice_log,json=ultimoIndiceLog,proto3" json:"ultimo_indice_log,omitempty"`
	UltimoTerminoLog int32                  `protobuf:"varint,4,opt,name=ultimo_termino_log,json=ultimoTerminoLog,proto3" json:"ultimo_termino_log,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SolicitudVoto) Reset() {
	*x = SolicitudVoto{}
	mi := &file_proto_aeroDist_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudVoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudVoto) ProtoMessage() {}

func (x *SolicitudVoto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudVoto.ProtoReflect.Descriptor instead.
func (*SolicitudVoto) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{28}
}

func (x *SolicitudVoto) GetTermino() int32 {
	if x != nil {
		return x.Termino
	}
	return 0
}

func (x *SolicitudVoto) GetCandidatoId() string {
	if x != nil {
		return x.CandidatoId
	}
	return ""
}

func (x *SolicitudVoto) GetUltimoIndiceLog() int32 {
	if x != nil {
		return x.UltimoIndiceLog
	}
	return 0
}

func (x *SolicitudVoto) GetUltimoTerminoLog() int32 {
	if x != nil {
		return x.UltimoTerminoLog
	}
	return 0
}

type RespuestaVoto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Termino       int32                  `protobuf:"varint,1,opt,name=termino,proto3" json:"termino,omitempty"`
	VotoConcedido bool                   `protobuf:"varint,2,opt,name=voto_concedido,json=votoConcedido,proto3" json:"voto_concedido,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaVoto) Reset() {
	*x = RespuestaVoto{}
	mi := &file_proto_aeroDist_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaVoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaVoto) ProtoMessage() {}

func (x *RespuestaVoto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaVoto.ProtoReflect.Descriptor instead.
func (*RespuestaVoto) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{29}
}

func (x *RespuestaVoto) GetTermino() int32 {
	if x != nil {
		return x.Termino
	}
	return 0
}

func (x *RespuestaVoto) GetVotoConcedido() bool {
	if x != nil {
		return x.VotoConcedido
	}
	return false
}

type SolicitudAppendEntries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Termino       int32                  `protobuf:"varint,1,opt,name=termino,proto3" json:"termino,omitempty"`
	LiderId       string                 `protobuf:"bytes,2,opt,name=lider_id,json=liderId,proto3" json:"lider_id,omitempty"`
	IndicePrevio  int32                  `protobuf:"varint,3,opt,name=indice_previo,json=indicePrevio,proto3" json:"indice_previo,omitempty"`
	TerminoPrevio int32                  `protobuf:"varint,4,opt,name=termino_previo,json=terminoPrevio,proto3" json:"termino_previo,omitempty"`
	Entradas      []*EntradaLog          `protobuf:"bytes,5,rep,name=entradas,proto3" json:"entradas,omitempty"`
	CommitIndex   int32                  `protobuf:"varint,6,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudAppendEntries) Reset() {
	*x = SolicitudAppendEntries{}
	mi := &file_proto_aeroDist_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudAppendEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudAppendEntries) ProtoMessage() {}

func (x *SolicitudAppendEntries) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudAppendEntries.ProtoReflect.Descriptor instead.
func (*SolicitudAppendEntries) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{30}
}

func (x *SolicitudAppendEntries) GetTermino() int32 {
	if x != nil {
		return x.Termino
	}
	return 0
}

func (x *SolicitudAppendEntries) GetLiderId() string {
	if x != nil {
		return x.LiderId
	}
	return ""
}

func (x *SolicitudAppendEntries) GetIndicePrevio() int32 {
	if x != nil {
		return x.IndicePrevio
	}
	return 0
}

func (x *SolicitudAppendEntries) GetTerminoPrevio() int32 {
	if x != nil {
		return x.TerminoPrevio
	}
	return 0
}

func (x *SolicitudAppendEntries) GetEntradas() []*EntradaLog {
	if x != nil {
		return x.Entradas
	}
	return nil
}

func (x *SolicitudAppendEntries) GetCommitIndex() int32 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

type RespuestaAppendEntries struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Termino           int32                  `protobuf:"varint,1,opt,name=termino,proto3" json:"termino,omitempty"`
	Exito             bool                   `protobuf:"varint,2,opt,name=exito,proto3" json:"exito,omitempty"`
	IndiceCoincidente int32                  `protobuf:"varint,3,opt,name=indice_coincidente,json=indiceCoincidente,proto3" json:"indice_coincidente,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RespuestaAppendEntries) Reset() {
	*x = RespuestaAppendEntries{}
	mi := &file_proto_aeroDist_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaAppendEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaAppendEntries) ProtoMessage() {}

func (x *RespuestaAppendEntries) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaAppendEntries.ProtoReflect.Descriptor instead.
func (*RespuestaAppendEntries) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{31}
}

func (x *RespuestaAppendEntries) GetTermino() int32 {
	if x != nil {
		return x.Termino
	}
	return 0
}

func (x *RespuestaAppendEntries) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *RespuestaAppendEntries) GetIndiceCoincidente() int32 {
	if x != nil {
		return x.IndiceCoincidente
	}
	return 0
}

type PropuestaOperacion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TipoOperacion string                 `protobuf:"bytes,1,opt,name=tipo_operacion,json=tipoOperacion,proto3" json:"tipo_operacion,omitempty"`
	VueloId       string                 `protobuf:"bytes,2,opt,name=vuelo_id,json=vueloId,proto3" json:"vuelo_id,omitempty"`
	EstadoVuelo   string                 `protobuf:"bytes,3,opt,name=estado_vuelo,json=estadoVuelo,proto3" json:"estado_vuelo,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropuestaOperacion) Reset() {
	*x = PropuestaOperacion{}
	mi := &file_proto_aeroDist_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropuestaOperacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropuestaOperacion) ProtoMessage() {}

func (x *PropuestaOperacion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropuestaOperacion.ProtoReflect.Descriptor instead.
func (*PropuestaOperacion) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{32}
}

func (x *PropuestaOperacion) GetTipoOperacion() string {
	if x != nil {
		return x.TipoOperacion
	}
	return ""
}

func (x *PropuestaOperacion) GetVueloId() string {
	if x != nil {
		return x.VueloId
	}
	return ""
}

func (x *PropuestaOperacion) GetEstadoVuelo() string {
	if x != nil {
		return x.EstadoVuelo
	}
	return ""
}

func (x *PropuestaOperacion) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type RespuestaPropuesta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	PistaAsignada string                 `protobuf:"bytes,3,opt,name=pista_asignada,json=pistaAsignada,proto3" json:"pista_asignada,omitempty"`
	Redirigir     bool                   `protobuf:"varint,4,opt,name=redirigir,proto3" json:"redirigir,omitempty"`
	LiderActual   string                 `protobuf:"bytes,5,opt,name=lider_actual,json=liderActual,proto3" json:"lider_actual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaPropuesta) Reset() {
	*x = RespuestaPropuesta{}
	mi := &file_proto_aeroDist_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaPropuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaPropuesta) ProtoMessage() {}

func (x *RespuestaPropuesta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaPropuesta.ProtoReflect.Descriptor instead.
func (*RespuestaPropuesta) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{33}
}

func (x *RespuestaPropuesta) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *RespuestaPropuesta) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *RespuestaPropuesta) GetPistaAsignada() string {
	if x != nil {
		return x.PistaAsignada
	}
	return ""
}

func (x *RespuestaPropuesta) GetRedirigir() bool {
	if x != nil {
		return x.Redirigir
	}
	return false
}

func (x *RespuestaPropuesta) GetLiderActual() string {
	if x != nil {
		return x.LiderActual
	}
	return ""
}

type EntradaLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indice        int32                  `protobuf:"varint,1,opt,name=indice,proto3" json:"indice,omitempty"`
	Termino       int32                  `protobuf:"varint,2,opt,name=termino,proto3" json:"termino,omitempty"`
	Comando       string                 `protobuf:"bytes,3,opt,name=comando,proto3" json:"comando,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntradaLog) Reset() {
	*x = EntradaLog{}
	mi := &file_proto_aeroDist_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntradaLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntradaLog) ProtoMessage() {}

func (x *EntradaLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntradaLog.ProtoReflect.Descriptor instead.
func (*EntradaLog) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{34}
}

func (x *EntradaLog) GetIndice() int32 {
	if x != nil {
		return x.Indice
	}
	return 0
}

func (x *EntradaLog) GetTermino() int32 {
	if x != nil {
		return x.Termino
	}
	return 0
}

func (x *EntradaLog) GetComando() string {
	if x != nil {
		return x.Comando
	}
	return ""
}

type SolicitudPista struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VueloId         string                 `protobuf:"bytes,1,opt,name=vuelo_id,json=vueloId,proto3" json:"vuelo_id,omitempty"`
	PistaSolicitada string                 `protobuf:"bytes,2,opt,name=pista_solicitada,json=pistaSolicitada,proto3" json:"pista_solicitada,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SolicitudPista) Reset() {
	*x = SolicitudPista{}
	mi := &file_proto_aeroDist_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudPista) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudPista) ProtoMessage() {}

func (x *SolicitudPista) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudPista.ProtoReflect.Descriptor instead.
func (*SolicitudPista) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{35}
}

func (x *SolicitudPista) GetVueloId() string {
	if x != nil {
		return x.VueloId
	}
	return ""
}

func (x *SolicitudPista) GetPistaSolicitada() string {
	if x != nil {
		return x.PistaSolicitada
	}
	return ""
}

type SolicitudLiberar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VueloId       string                 `protobuf:"bytes,1,opt,name=vuelo_id,json=vueloId,proto3" json:"vuelo_id,omitempty"`
	PistaId       string                 `protobuf:"bytes,2,opt,name=pista_id,json=pistaId,proto3" json:"pista_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudLiberar) Reset() {
	*x = SolicitudLiberar{}
	mi := &file_proto_aeroDist_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudLiberar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudLiberar) ProtoMessage() {}

func (x *SolicitudLiberar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudLiberar.ProtoReflect.Descriptor instead.
func (*SolicitudLiberar) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{36}
}

func (x *SolicitudLiberar) GetVueloId() string {
	if x != nil {
		return x.VueloId
	}
	return ""
}

func (x *SolicitudLiberar) GetPistaId() string {
	if x != nil {
		return x.PistaId
	}
	return ""
}

type RespuestaPista struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	PistaAsignada string                 `protobuf:"bytes,3,opt,name=pista_asignada,json=pistaAsignada,proto3" json:"pista_asignada,omitempty"`
	Redirigir     bool                   `protobuf:"varint,4,opt,name=redirigir,proto3" json:"redirigir,omitempty"`
	LiderActual   string                 `protobuf:"bytes,5,opt,name=lider_actual,json=liderActual,proto3" json:"lider_actual,omitempty"`
	PistaOcupada  bool                   `protobuf:"varint,6,opt,name=pista_ocupada,json=pistaOcupada,proto3" json:"pista_ocupada,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaPista) Reset() {
	*x = RespuestaPista{}
	mi := &file_proto_aeroDist_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaPista) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaPista) ProtoMessage() {}

func (x *RespuestaPista) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aeroDist_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaPista.ProtoReflect.Descriptor instead.
func (*RespuestaPista) Descriptor() ([]byte, []int) {
	return file_proto_aeroDist_proto_rawDescGZIP(), []int{37}
}

func (x *RespuestaPista) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *RespuestaPista) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *RespuestaPista) GetPistaAsignada() string {
	if x != nil {
		return x.PistaAsignada
	}
	return ""
}

func (x *RespuestaPista) GetRedirigir() bool {
	if x != nil {
		return x.Redirigir
	}
	return false
}

func (x *RespuestaPista) GetLiderActual() string {
	if x != nil {
		return x.LiderActual
	}
	return ""
}

func (x *RespuestaPista) GetPistaOcupada() bool {
	if x != nil {
		return x.PistaOcupada
	}
	return false
}

var File_proto_aeroDist_proto protoreflect.FileDescriptor

const file_proto_aeroDist_proto_rawDesc = "" +
	"\n" +
	"\x14proto/aeroDist.proto\x12\baeroDist\"q\n" +
	"\x0fRegistroRequest\x12!\n" +
	"\ftipo_entidad\x18\x01 \x01(\tR\vtipoEntidad\x12\x1d\n" +
	"\n" +
	"id_entidad\x18\x02 \x01(\tR\tidEntidad\x12\x1c\n" +
	"\tdireccion\x18\x03 \x01(\tR\tdireccion\"B\n" +
	"\x10RegistroResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"Q\n" +
	"\rInicioRequest\x12!\n" +
	"\ftipo_entidad\x18\x01 \x01(\tR\vtipoEntidad\x12\x1d\n" +
	"\n" +
	"id_entidad\x18\x02 \x01(\tR\tidEntidad\"O\n" +
	"\x0eInicioResponse\x12#\n" +
	"\rpuede_iniciar\x18\x01 \x01(\bR\fpuedeIniciar\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"\x87\x01\n" +
	"\x14EstadoInicialRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\x12\x19\n" +
	"\bvuelo_id\x18\x02 \x01(\tR\avueloId\x125\n" +
	"\vsticky_info\x18\x03 \x01(\v2\x14.aeroDist.StickyInfoR\n" +
	"stickyInfo\"\xce\x01\n" +
	"\x15EstadoInicialResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x121\n" +
	"\x14asientos_disponibles\x18\x03 \x03(\tR\x13asientosDisponibles\x12%\n" +
	"\x0etotal_asientos\x18\x04 \x01(\x05R\rtotalAsientos\x12+\n" +
	"\x11asientos_ocupados\x18\x05 \x01(\x05R\x10asientosOcupados\"y\n" +
	"\n" +
	"StickyInfo\x12!\n" +
	"\ftiene_sesion\x18\x01 \x01(\bR\vtieneSesion\x12)\n" +
	"\x10datanode_address\x18\x02 \x01(\tR\x0fdatanodeAddress\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x03 \x01(\tR\tclienteId\"\xba\x01\n" +
	"\x0eCheckInRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\x12\x19\n" +
	"\bvuelo_id\x18\x02 \x01(\tR\avueloId\x12\x18\n" +
	"\aasiento\x18\x03 \x01(\tR\aasiento\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x125\n" +
	"\vsticky_info\x18\x05 \x01(\v2\x14.aeroDist.StickyInfoR\n" +
	"stickyInfo\"^\n" +
	"\x12DatanodeAsignacion\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\x12)\n" +
	"\x10datanode_address\x18\x02 \x01(\tR\x0fdatanodeAddress\"\xda\x01\n" +
	"\x0fCheckInResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12.\n" +
	"\x13tarjeta_embarque_id\x18\x03 \x01(\tR\x11tarjetaEmbarqueId\x12)\n" +
	"\x10asiento_asignado\x18\x04 \x01(\tR\x0fasientoAsignado\x12<\n" +
	"\n" +
	"asignacion\x18\x05 \x01(\v2\x1c.aeroDist.DatanodeAsignacionR\n" +
	"asignacion\"\x96\x01\n" +
	"\x0eTarjetaRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\x12.\n" +
	"\x13tarjeta_embarque_id\x18\x02 \x01(\tR\x11tarjetaEmbarqueId\x125\n" +
	"\vsticky_info\x18\x03 \x01(\v2\x14.aeroDist.StickyInfoR\n" +
	"stickyInfo\"\xad\x01\n" +
	"\x0fTarjetaResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12\x19\n" +
	"\bvuelo_id\x18\x03 \x01(\tR\avueloId\x12\x18\n" +
	"\aasiento\x18\x04 \x01(\tR\aasiento\x12\x16\n" +
	"\x06estado\x18\x05 \x01(\tR\x06estado\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x06 \x01(\tR\tclienteId\",\n" +
	"\x0fAsientosRequest\x12\x19\n" +
	"\bvuelo_id\x18\x01 \x01(\tR\avueloId\"\x91\x02\n" +
	"\x10AsientosResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x121\n" +
	"\x14asientos_disponibles\x18\x03 \x03(\tR\x13asientosDisponibles\x12W\n" +
	"\x0festado_asientos\x18\x04 \x03(\v2..aeroDist.AsientosResponse.EstadoAsientosEntryR\x0eestadoAsientos\x1aA\n" +
	"\x13EstadoAsientosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x83\x01\n" +
	"\x0eReservaRequest\x12\x19\n" +
	"\bvuelo_id\x18\x01 \x01(\tR\avueloId\x12\x18\n" +
	"\aasiento\x18\x02 \x01(\tR\aasiento\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x03 \x01(\tR\tclienteId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"q\n" +
	"\x0fReservaResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12.\n" +
	"\x13tarjeta_embarque_id\x18\x03 \x01(\tR\x11tarjetaEmbarqueId\"B\n" +
	"\x10InfoVueloRequest\x12.\n" +
	"\x13tarjeta_embarque_id\x18\x01 \x01(\tR\x11tarjetaEmbarqueId\"\xaf\x01\n" +
	"\x11InfoVueloResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12\x19\n" +
	"\bvuelo_id\x18\x03 \x01(\tR\avueloId\x12\x18\n" +
	"\aasiento\x18\x04 \x01(\tR\aasiento\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x05 \x01(\tR\tclienteId\x12\x16\n" +
	"\x06estado\x18\x06 \x01(\tR\x06estado\"\xd6\x01\n" +
	"\x19ActualizacionVueloRequest\x12\x19\n" +
	"\bvuelo_id\x18\x01 \x01(\tR\avueloId\x12\x1f\n" +
	"\vupdate_type\x18\x02 \x01(\tR\n" +
	"updateType\x12!\n" +
	"\fupdate_value\x18\x03 \x01(\tR\vupdateValue\x12 \n" +
	"\fsim_time_sec\x18\x04 \x01(\x03R\n" +
	"simTimeSec\x128\n" +
	"\freloj_vector\x18\x05 \x01(\v2\x15.aeroDist.VectorClockR\vrelojVector\"\x84\x01\n" +
	"\x1aActualizacionVueloResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x126\n" +
	"\vnuevo_reloj\x18\x03 \x01(\v2\x15.aeroDist.VectorClockR\n" +
	"nuevoReloj\"\x83\x01\n" +
	"\vVectorClock\x129\n" +
	"\x06clocks\x18\x01 \x03(\v2!.aeroDist.VectorClock.ClocksEntryR\x06clocks\x1a9\n" +
	"\vClocksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x98\x02\n" +
	"\x0eEstadoDatanode\x12R\n" +
	"\x0eestados_vuelos\x18\x01 \x03(\v2+.aeroDist.EstadoDatanode.EstadosVuelosEntryR\restadosVuelos\x128\n" +
	"\freloj_vector\x18\x02 \x01(\v2\x15.aeroDist.VectorClockR\vrelojVector\x12\x1f\n" +
	"\vdatanode_id\x18\x03 \x01(\tR\n" +
	"datanodeId\x1aW\n" +
	"\x12EstadosVuelosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.aeroDist.EstadoVueloR\x05value:\x028\x01\"\xf8\x03\n" +
	"\vEstadoVuelo\x12#\n" +
	"\rultimo_estado\x18\x01 \x01(\tR\fultimoEstado\x12#\n" +
	"\rultima_puerta\x18\x02 \x01(\tR\fultimaPuerta\x128\n" +
	"\freloj_estado\x18\x03 \x01(\v2\x15.aeroDist.VectorClockR\vrelojEstado\x121\n" +
	"\x14ultima_actualizacion\x18\x04 \x01(\x03R\x13ultimaActualizacion\x12X\n" +
	"\x11asientos_ocupados\x18\x05 \x03(\v2+.aeroDist.EstadoVuelo.AsientosOcupadosEntryR\x10asientosOcupados\x12?\n" +
	"\btarjetas\x18\x06 \x03(\v2#.aeroDist.EstadoVuelo.TarjetasEntryR\btarjetas\x1aC\n" +
	"\x15AsientosOcupadosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1aR\n" +
	"\rTarjetasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.aeroDist.TarjetaInfoR\x05value:\x028\x01\"\x7f\n" +
	"\vTarjetaInfo\x12\x19\n" +
	"\bvuelo_id\x18\x01 \x01(\tR\avueloId\x12\x18\n" +
	"\aasiento\x18\x02 \x01(\tR\aasiento\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x03 \x01(\tR\tclienteId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x85\x01\n" +
	"\x15SincronizacionRequest\x12C\n" +
	"\x10estado_remitente\x18\x01 \x01(\v2\x18.aeroDist.EstadoDatanodeR\x0festadoRemitente\x12'\n" +
	"\x0fdatanode_origen\x18\x02 \x01(\tR\x0edatanodeOrigen\"\x91\x01\n" +
	"\x16SincronizacionResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12G\n" +
	"\x12estado_actualizado\x18\x03 \x01(\v2\x18.aeroDist.EstadoDatanodeR\x11estadoActualizado\"\x8e\x01\n" +
	"\x12EstadoVueloRequest\x12\x19\n" +
	"\bvuelo_id\x18\x01 \x01(\tR\avueloId\x12>\n" +
	"\x0fversion_cliente\x18\x02 \x01(\v2\x15.aeroDist.VectorClockR\x0eversionCliente\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x03 \x01(\tR\tclienteId\"\xce\x01\n" +
	"\x13EstadoVueloResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12\x19\n" +
	"\bvuelo_id\x18\x03 \x01(\tR\avueloId\x12\x16\n" +
	"\x06estado\x18\x04 \x01(\tR\x06estado\x12\x16\n" +
	"\x06puerta\x18\x05 \x01(\tR\x06puerta\x12<\n" +
	"\x0eversion_actual\x18\x06 \x01(\v2\x15.aeroDist.VectorClockR\rversionActual\"\xa6\x01\n" +
	"\rSolicitudVoto\x12\x18\n" +
	"\atermino\x18\x01 \x01(\x05R\atermino\x12!\n" +
	"\fcandidato_id\x18\x02 \x01(\tR\vcandidatoId\x12*\n" +
	"\x11ultimo_indice_log\x18\x03 \x01(\x05R\x0fultimoIndiceLog\x12,\n" +
	"\x12ultimo_termino_log\x18\x04 \x01(\x05R\x10ultimoTerminoLog\"P\n" +
	"\rRespuestaVoto\x12\x18\n" +
	"\atermino\x18\x01 \x01(\x05R\atermino\x12%\n" +
	"\x0evoto_concedido\x18\x02 \x01(\bR\rvotoConcedido\"\xee\x01\n" +
	"\x16SolicitudAppendEntries\x12\x18\n" +
	"\atermino\x18\x01 \x01(\x05R\atermino\x12\x19\n" +
	"\blider_id\x18\x02 \x01(\tR\aliderId\x12#\n" +
	"\rindice_previo\x18\x03 \x01(\x05R\findicePrevio\x12%\n" +
	"\x0etermino_previo\x18\x04 \x01(\x05R\rterminoPrevio\x120\n" +
	"\bentradas\x18\x05 \x03(\v2\x14.aeroDist.EntradaLogR\bentradas\x12!\n" +
	"\fcommit_index\x18\x06 \x01(\x05R\vcommitIndex\"w\n" +
	"\x16RespuestaAppendEntries\x12\x18\n" +
	"\atermino\x18\x01 \x01(\x05R\atermino\x12\x14\n" +
	"\x05exito\x18\x02 \x01(\bR\x05exito\x12-\n" +
	"\x12indice_coincidente\x18\x03 \x01(\x05R\x11indiceCoincidente\"\x97\x01\n" +
	"\x12PropuestaOperacion\x12%\n" +
	"\x0etipo_operacion\x18\x01 \x01(\tR\rtipoOperacion\x12\x19\n" +
	"\bvuelo_id\x18\x02 \x01(\tR\avueloId\x12!\n" +
	"\festado_vuelo\x18\x03 \x01(\tR\vestadoVuelo\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"\xac\x01\n" +
	"\x12RespuestaPropuesta\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12%\n" +
	"\x0epista_asignada\x18\x03 \x01(\tR\rpistaAsignada\x12\x1c\n" +
	"\tredirigir\x18\x04 \x01(\bR\tredirigir\x12!\n" +
	"\flider_actual\x18\x05 \x01(\tR\vliderActual\"X\n" +
	"\n" +
	"EntradaLog\x12\x16\n" +
	"\x06indice\x18\x01 \x01(\x05R\x06indice\x12\x18\n" +
	"\atermino\x18\x02 \x01(\x05R\atermino\x12\x18\n" +
	"\acomando\x18\x03 \x01(\tR\acomando\"V\n" +
	"\x0eSolicitudPista\x12\x19\n" +
	"\bvuelo_id\x18\x01 \x01(\tR\avueloId\x12)\n" +
	"\x10pista_solicitada\x18\x02 \x01(\tR\x0fpistaSolicitada\"H\n" +
	"\x10SolicitudLiberar\x12\x19\n" +
	"\bvuelo_id\x18\x01 \x01(\tR\avueloId\x12\x19\n" +
	"\bpista_id\x18\x02 \x01(\tR\apistaId\"\xcd\x01\n" +
	"\x0eRespuestaPista\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12%\n" +
	"\x0epista_asignada\x18\x03 \x01(\tR\rpistaAsignada\x12\x1c\n" +
	"\tredirigir\x18\x04 \x01(\bR\tredirigir\x12!\n" +
	"\flider_actual\x18\x05 \x01(\tR\vliderActual\x12#\n" +
	"\rpista_ocupada\x18\x06 \x01(\bR\fpistaOcupada2\x86\n" +
	"\n" +
	"\bAeroDist\x12I\n" +
	"\x10RegistrarEntidad\x12\x19.aeroDist.RegistroRequest\x1a\x1a.aeroDist.RegistroResponse\x12D\n" +
	"\x0fSolicitarInicio\x12\x17.aeroDist.InicioRequest\x1a\x18.aeroDist.InicioResponse\x12W\n" +
	"\x14ObtenerEstadoInicial\x12\x1e.aeroDist.EstadoInicialRequest\x1a\x1f.aeroDist.EstadoInicialResponse\x12F\n" +
	"\x0fRealizarCheckIn\x12\x18.aeroDist.CheckInRequest\x1a\x19.aeroDist.CheckInResponse\x12M\n" +
	"\x16ObtenerTarjetaEmbarque\x12\x18.aeroDist.TarjetaRequest\x1a\x19.aeroDist.TarjetaResponse\x12S\n" +
	"\x1aObtenerAsientosDisponibles\x12\x19.aeroDist.AsientosRequest\x1a\x1a.aeroDist.AsientosResponse\x12F\n" +
	"\x0fReservarAsiento\x12\x18.aeroDist.ReservaRequest\x1a\x19.aeroDist.ReservaResponse\x12R\n" +
	"\x17ObtenerInformacionVuelo\x12\x1a.aeroDist.InfoVueloRequest\x1a\x1b.aeroDist.InfoVueloResponse\x12e\n" +
	"\x18EnviarActualizacionVuelo\x12#.aeroDist.ActualizacionVueloRequest\x1a$.aeroDist.ActualizacionVueloResponse\x12V\n" +
	"\x11SincronizarEstado\x12\x1f.aeroDist.SincronizacionRequest\x1a .aeroDist.SincronizacionResponse\x12Q\n" +
	"\x12ObtenerEstadoVuelo\x12\x1c.aeroDist.EstadoVueloRequest\x1a\x1d.aeroDist.EstadoVueloResponse\x12A\n" +
	"\rSolicitarVoto\x12\x17.aeroDist.SolicitudVoto\x1a\x17.aeroDist.RespuestaVoto\x12S\n" +
	"\rAppendEntries\x12 .aeroDist.SolicitudAppendEntries\x1a .aeroDist.RespuestaAppendEntries\x12T\n" +
	"\x16ProponerOperacionPista\x12\x1c.aeroDist.PropuestaOperacion\x1a\x1c.aeroDist.RespuestaPropuesta\x12B\n" +
	"\fAsignarPista\x12\x18.aeroDist.SolicitudPista\x1a\x18.aeroDist.RespuestaPista\x12D\n" +
	"\fLiberarPista\x12\x1a.aeroDist.SolicitudLiberar\x1a\x18.aeroDist.RespuestaPistaB\bZ\x06proto/b\x06proto3"

var (
	file_proto_aeroDist_proto_rawDescOnce sync.Once
	file_proto_aeroDist_proto_rawDescData []byte
)

func file_proto_aeroDist_proto_rawDescGZIP() []byte {
	file_proto_aeroDist_proto_rawDescOnce.Do(func() {
		file_proto_aeroDist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_aeroDist_proto_rawDesc), len(file_proto_aeroDist_proto_rawDesc)))
	})
	return file_proto_aeroDist_proto_rawDescData
}

var file_proto_aeroDist_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_proto_aeroDist_proto_goTypes = []any{
	(*RegistroRequest)(nil),            // 0: aeroDist.RegistroRequest
	(*RegistroResponse)(nil),           // 1: aeroDist.RegistroResponse
	(*InicioRequest)(nil),              // 2: aeroDist.InicioRequest
	(*InicioResponse)(nil),             // 3: aeroDist.InicioResponse
	(*EstadoInicialRequest)(nil),       // 4: aeroDist.EstadoInicialRequest
	(*EstadoInicialResponse)(nil),      // 5: aeroDist.EstadoInicialResponse
	(*StickyInfo)(nil),                 // 6: aeroDist.StickyInfo
	(*CheckInRequest)(nil),             // 7: aeroDist.CheckInRequest
	(*DatanodeAsignacion)(nil),         // 8: aeroDist.DatanodeAsignacion
	(*CheckInResponse)(nil),            // 9: aeroDist.CheckInResponse
	(*TarjetaRequest)(nil),             // 10: aeroDist.TarjetaRequest
	(*TarjetaResponse)(nil),            // 11: aeroDist.TarjetaResponse
	(*AsientosRequest)(nil),            // 12: aeroDist.AsientosRequest
	(*AsientosResponse)(nil),           // 13: aeroDist.AsientosResponse
	(*ReservaRequest)(nil),             // 14: aeroDist.ReservaRequest
	(*ReservaResponse)(nil),            // 15: aeroDist.ReservaResponse
	(*InfoVueloRequest)(nil),           // 16: aeroDist.InfoVueloRequest
	(*InfoVueloResponse)(nil),          // 17: aeroDist.InfoVueloResponse
	(*ActualizacionVueloRequest)(nil),  // 18: aeroDist.ActualizacionVueloRequest
	(*ActualizacionVueloResponse)(nil), // 19: aeroDist.ActualizacionVueloResponse
	(*VectorClock)(nil),                // 20: aeroDist.VectorClock
	(*EstadoDatanode)(nil),             // 21: aeroDist.EstadoDatanode
	(*EstadoVuelo)(nil),                // 22: aeroDist.EstadoVuelo
	(*TarjetaInfo)(nil),                // 23: aeroDist.TarjetaInfo
	(*SincronizacionRequest)(nil),      // 24: aeroDist.SincronizacionRequest
	(*SincronizacionResponse)(nil),     // 25: aeroDist.SincronizacionResponse
	(*EstadoVueloRequest)(nil),         // 26: aeroDist.EstadoVueloRequest
	(*EstadoVueloResponse)(nil),        // 27: aeroDist.EstadoVueloResponse
	(*SolicitudVoto)(nil),              // 28: aeroDist.SolicitudVoto
	(*RespuestaVoto)(nil),              // 29: aeroDist.RespuestaVoto
	(*SolicitudAppendEntries)(nil),     // 30: aeroDist.SolicitudAppendEntries
	(*RespuestaAppendEntries)(nil),     // 31: aeroDist.RespuestaAppendEntries
	(*PropuestaOperacion)(nil),         // 32: aeroDist.PropuestaOperacion
	(*RespuestaPropuesta)(nil),         // 33: aeroDist.RespuestaPropuesta
	(*EntradaLog)(nil),                 // 34: aeroDist.EntradaLog
	(*SolicitudPista)(nil),             // 35: aeroDist.SolicitudPista
	(*SolicitudLiberar)(nil),           // 36: aeroDist.SolicitudLiberar
	(*RespuestaPista)(nil),             // 37: aeroDist.RespuestaPista
	nil,                                // 38: aeroDist.AsientosResponse.EstadoAsientosEntry
	nil,                                // 39: aeroDist.VectorClock.ClocksEntry
	nil,                                // 40: aeroDist.EstadoDatanode.EstadosVuelosEntry
	nil,                                // 41: aeroDist.EstadoVuelo.AsientosOcupadosEntry
	nil,                                // 42: aeroDist.EstadoVuelo.TarjetasEntry
}
var file_proto_aeroDist_proto_depIdxs = []int32{
	6,  // 0: aeroDist.EstadoInicialRequest.sticky_info:type_name -> aeroDist.StickyInfo
	6,  // 1: aeroDist.CheckInRequest.sticky_info:type_name -> aeroDist.StickyInfo
	8,  // 2: aeroDist.CheckInResponse.asignacion:type_name -> aeroDist.DatanodeAsignacion
	6,  // 3: aeroDist.TarjetaRequest.sticky_info:type_name -> aeroDist.StickyInfo
	38, // 4: aeroDist.AsientosResponse.estado_asientos:type_name -> aeroDist.AsientosResponse.EstadoAsientosEntry
	20, // 5: aeroDist.ActualizacionVueloRequest.reloj_vector:type_name -> aeroDist.VectorClock
	20, // 6: aeroDist.ActualizacionVueloResponse.nuevo_reloj:type_name -> aeroDist.VectorClock
	39, // 7: aeroDist.VectorClock.clocks:type_name -> aeroDist.VectorClock.ClocksEntry
	40, // 8: aeroDist.EstadoDatanode.estados_vuelos:type_name -> aeroDist.EstadoDatanode.EstadosVuelosEntry
	20, // 9: aeroDist.EstadoDatanode.reloj_vector:type_name -> aeroDist.VectorClock
	20, // 10: aeroDist.EstadoVuelo.reloj_estado:type_name -> aeroDist.VectorClock
	41, // 11: aeroDist.EstadoVuelo.asientos_ocupados:type_name -> aeroDist.EstadoVuelo.AsientosOcupadosEntry
	42, // 12: aeroDist.EstadoVuelo.tarjetas:type_name -> aeroDist.EstadoVuelo.TarjetasEntry
	21, // 13: aeroDist.SincronizacionRequest.estado_remitente:type_name -> aeroDist.EstadoDatanode
	21, // 14: aeroDist.SincronizacionResponse.estado_actualizado:type_name -> aeroDist.EstadoDatanode
	20, // 15: aeroDist.EstadoVueloRequest.version_cliente:type_name -> aeroDist.VectorClock
	20, // 16: aeroDist.EstadoVueloResponse.version_actual:type_name -> aeroDist.VectorClock
	34, // 17: aeroDist.SolicitudAppendEntries.entradas:type_name -> aeroDist.EntradaLog
	22, // 18: aeroDist.EstadoDatanode.EstadosVuelosEntry.value:type_name -> aeroDist.EstadoVuelo
	23, // 19: aeroDist.EstadoVuelo.TarjetasEntry.value:type_name -> aeroDist.TarjetaInfo
	0,  // 20: aeroDist.AeroDist.RegistrarEntidad:input_type -> aeroDist.RegistroRequest
	2,  // 21: aeroDist.AeroDist.SolicitarInicio:input_type -> aeroDist.InicioRequest
	4,  // 22: aeroDist.AeroDist.ObtenerEstadoInicial:input_type -> aeroDist.EstadoInicialRequest
	7,  // 23: aeroDist.AeroDist.RealizarCheckIn:input_type -> aeroDist.CheckInRequest
	10, // 24: aeroDist.AeroDist.ObtenerTarjetaEmbarque:input_type -> aeroDist.TarjetaRequest
	12, // 25: aeroDist.AeroDist.ObtenerAsientosDisponibles:input_type -> aeroDist.AsientosRequest
	14, // 26: aeroDist.AeroDist.ReservarAsiento:input_type -> aeroDist.ReservaRequest
	16, // 27: aeroDist.AeroDist.ObtenerInformacionVuelo:input_type -> aeroDist.InfoVueloRequest
	18, // 28: aeroDist.AeroDist.EnviarActualizacionVuelo:input_type -> aeroDist.ActualizacionVueloRequest
	24, // 29: aeroDist.AeroDist.SincronizarEstado:input_type -> aeroDist.SincronizacionRequest
	26, // 30: aeroDist.AeroDist.ObtenerEstadoVuelo:input_type -> aeroDist.EstadoVueloRequest
	28, // 31: aeroDist.AeroDist.SolicitarVoto:input_type -> aeroDist.SolicitudVoto
	30, // 32: aeroDist.AeroDist.AppendEntries:input_type -> aeroDist.SolicitudAppendEntries
	32, // 33: aeroDist.AeroDist.ProponerOperacionPista:input_type -> aeroDist.PropuestaOperacion
	35, // 34: aeroDist.AeroDist.AsignarPista:input_type -> aeroDist.SolicitudPista
	36, // 35: aeroDist.AeroDist.LiberarPista:input_type -> aeroDist.SolicitudLiberar
	1,  // 36: aeroDist.AeroDist.RegistrarEntidad:output_type -> aeroDist.RegistroResponse
	3,  // 37: aeroDist.AeroDist.SolicitarInicio:output_type -> aeroDist.InicioResponse
	5,  // 38: aeroDist.AeroDist.ObtenerEstadoInicial:output_type -> aeroDist.EstadoInicialResponse
	9,  // 39: aeroDist.AeroDist.RealizarCheckIn:output_type -> aeroDist.CheckInResponse
	11, // 40: aeroDist.AeroDist.ObtenerTarjetaEmbarque:output_type -> aeroDist.TarjetaResponse
	13, // 41: aeroDist.AeroDist.ObtenerAsientosDisponibles:output_type -> aeroDist.AsientosResponse
	15, // 42: aeroDist.AeroDist.ReservarAsiento:output_type -> aeroDist.ReservaResponse
	17, // 43: aeroDist.AeroDist.ObtenerInformacionVuelo:output_type -> aeroDist.InfoVueloResponse
	19, // 44: aeroDist.AeroDist.EnviarActualizacionVuelo:output_type -> aeroDist.ActualizacionVueloResponse
	25, // 45: aeroDist.AeroDist.SincronizarEstado:output_type -> aeroDist.SincronizacionResponse
	27, // 46: aeroDist.AeroDist.ObtenerEstadoVuelo:output_type -> aeroDist.EstadoVueloResponse
	29, // 47: aeroDist.AeroDist.SolicitarVoto:output_type -> aeroDist.RespuestaVoto
	31, // 48: aeroDist.AeroDist.AppendEntries:output_type -> aeroDist.RespuestaAppendEntries
	33, // 49: aeroDist.AeroDist.ProponerOperacionPista:output_type -> aeroDist.RespuestaPropuesta
	37, // 50: aeroDist.AeroDist.AsignarPista:output_type -> aeroDist.RespuestaPista
	37, // 51: aeroDist.AeroDist.LiberarPista:output_type -> aeroDist.RespuestaPista
	36, // [36:52] is the sub-list for method output_type
	20, // [20:36] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_aeroDist_proto_init() }
func file_proto_aeroDist_proto_init() {
	if File_proto_aeroDist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_aeroDist_proto_rawDesc), len(file_proto_aeroDist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_aeroDist_proto_goTypes,
		DependencyIndexes: file_proto_aeroDist_proto_depIdxs,
		MessageInfos:      file_proto_aeroDist_proto_msgTypes,
	}.Build()
	File_proto_aeroDist_proto = out.File
	file_proto_aeroDist_proto_goTypes = nil
	file_proto_aeroDist_proto_depIdxs = nil
}
